### ISSUE TITLE
Required and optional track info should be displayed and configured separately

### ISSUE THREAD

**Issue by SiteNEx** [Prifiz/NC_EDU_2016_17#17]
Минимальная инфа - Артист и Название. Остальное добавляется опционально.

**Comment by Prifiz** [comment]
Опиши сначала здесь, какой вариант разделения настроек выбрал

**Comment by VellkyPie** [comment]
Я решил реализовать через кнопку "Advanced". При её нажатии, будут открываться дополнительные поля для заполнения, продвинутым пользователем.
