### ISSUE TITLE
Use special UI controls for data types

### ISSUE THREAD

**Issue by SiteNEx** [Prifiz/NC_EDU_2016_17#18]
контролы - пользовательские элементы управления., т.е для года - соотв поле (с выбором через выпадающий список к примеру), времени - поле с форматом и т.д.

**Comment by Prifiz** [comment]
Никита, когда начнешь делать эту задачу, опиши сначала здесь, какой контрол для какой цели собираешься использовать. Заранее подумаем, как сделать лучше
