### ISSUE TITLE
Load TrackList from serialized file (4 SP)

### ISSUE THREAD

**Issue by SlavaKaryagin** [Prifiz/NC_EDU_2016_17#21]

**Comment by Prifiz** [comment]
Требования аналогичны Load из XML. Только, естественно, без XSD.
Если при десериализации возникли какие-то ошибки, то сообщаем пользователю, что файл имеет некорректный формат. Предложить выбрать другой.
Вообще было бы удобно сделать эти все Load/Save не кучей кнопой, а в виде меню сверху окна. Тогда можно логично выбирать. Например: File -> Load From... -> Serialized File
 ->XML File

**Comment by SiteNEx** [comment]
Сделал. Установил фильтр на выбор файлов определенного расширения. Если пользователь намеренно выберет файл с другим расширением - повалятся exceptions. Ах, да. Может еще быть файл с таким же расширением, но левый.. Хм, надо подумать - как поправить.

**Comment by Prifiz** [comment]
Видел реализацию. Считаем, что сделано.
