### ISSUE TITLE
Add "Remove Track" option (1.5 SP)

### ISSUE THREAD

**Issue by SlavaKaryagin** [Prifiz/NC_EDU_2016_17#22]

**Comment by Prifiz** [comment]
Должна быть возможность удалить выбранную в таблице запись.
При этом удаляем не напрямую из таблицы, а из модели.
Выбрали строку - нажали кнопку Remove. Далее в коллекции треков ищется тот, что выбрали, и удаляется. После чего таблица на форме обновляется.
При желании можно сделать диалог подтверждения.
