### ISSUE TITLE
Split project into Model and Application (1 SP)

### ISSUE THREAD

**Issue by SlavaKaryagin** [Prifiz/NC_EDU_2016_17#25]
CommonModel.jar и Application.jar

**Comment by Prifiz** [comment]
Напомню, что в CommonModel должны храниться все сущности, кроме коллекций, в которых они хранятся.
Алгоритм сборки должен быть одинаковый.
Все public-методы (здесь это пока только конструкторы классов) должны быть снабжены javadoc

**Comment by tr1ben** [comment]
Не разобрался. Вопрос на обсуждение
